// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlyogpwkvyuxipbdoyfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpseW9ncHdrdnl1eGlwYmRveWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NDQ2NjUsImV4cCI6MjA3NTUyMDY2NX0.BSE4VpQBf3j22Xb7tNseUAhs79BGy8-JyEFaYT7-tOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});